[project]
name = "quantish"
version = "0.1.0"
authors = [
  { name="Randy Gobbbel", email="randy.gobbel@gmail.com" },
]
description = "Quantish physics simulation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair==6.0.0",
    "anthropic==0.75.0",
    "arrow==1.4.0",
    "asttokens==3.0.1",
    "bleach==6.3.0",
    "click==8.3.1",
    "docutils==0.22.3",
    "ipykernel==7.1.0",
    "ipywidgets==8.1.8",
    "jupyterlab==4.5.0",
    "loro==1.10.0",
    "marimo==0.18.1",
    "matplotlib==3.10.7",
    "mermaid-py==0.8.0",
    "msgspec>=0.18.0",
    "pandas==2.3.3",
    "pandas-stubs==2.3.3.251201",
    "pyarrow==22.0.0",
    "python-dotenv>=1.0.0",
    "python-mermaid==0.1.6",
    "qiskit==2.2.3",
    "scipy==1.16.3",
    "scipy-stubs==1.16.3.2",
    "seaborn==0.13.2",
    "sympy==1.14.0",
    "tqdm>=4.67.1",
    "types-python-dateutil==2.9.0.20251115",
    "unpythonic==0.15.5",
    "widgetsnbextension==4.0.15",
]
